### ISSUE TITLE
Calling close() prints some error (in ssh2)

### ISSUE THREAD

**Issue by sp00x** [maitrungduc1410/node-scp-async#31]
Just a sample app that connects, the disconnects. Prints an error (**not** crashing, though) to the console when .close() is called:

I.e. code:

```ts
import { Client as ScpClient } from 'node-scp';
let c = await ScpClient({/* ..options here.. */});
await c.close();
```

Error being printed:

```
Error during closing sftpWrapper Error: No such file
    at 101 (####\node_modules\ssh2\lib\protocol\SFTP.js:2704:19)
    at SFTP.push (####\node_modules\ssh2\lib\protocol\SFTP.js:278:11)
    at CHANNEL_DATA (####\node_modules\ssh2\lib\client.js:525:23)
    at 94 (####\node_modules\ssh2\lib\protocol\handlers.misc.js:859:16)
    at Protocol.onPayload (####\node_modules\ssh2\lib\protocol\Protocol.js:2025:10)
    at AESGCMDecipherBinding.decrypt (####\node_modules\ssh2\lib\protocol\crypto.js:1086:26)
    at Protocol.parsePacket [as _parse] (####\node_modules\ssh2\lib\protocol\Protocol.js:1994:25)
    at Protocol.parse (####\node_modules\ssh2\lib\protocol\Protocol.js:293:16)
    at Socket.<anonymous> (####\node_modules\ssh2\lib\client.js:713:21)
    at Socket.emit (node:events:520:28) {
  code: 2
```

...which is from here: https://github.com/mscdex/ssh2/blob/master/lib/protocol/SFTP.js#L2704

Remote server is sshd on Debian, `OpenSSH_8.4p1 Debian-5+deb11u1, OpenSSL 1.1.1n  15 Mar 2022`

Compared the debug logging compared to what doing the same using the sftp example for `ssh2` and calling .end():

node-scp close():

```
Outbound: Sending CHANNEL_DATA (r:0, 14)
SFTP: Outbound: Buffered CLOSE
Outbound: Sending DISCONNECT (11)
Inbound: CHANNEL_DATA (r:0, 33)
SFTP: Inbound: Received STATUS (id:6, 2, "No such file")
Error during closing sftpWrapper Error: No such file
    at 101 (####\node_modules\ssh2\lib\protocol\SFTP.js:2704:19)
    at SFTP.push (####\node_modules\ssh2\lib\protocol\SFTP.js:278:11)
    at CHANNEL_DATA (####\node_modules\ssh2\lib\client.js:525:23)
    at 94 (####\node_modules\ssh2\lib\protocol\handlers.misc.js:859:16)
    at Protocol.onPayload (####\node_modules\ssh2\lib\protocol\Protocol.js:2025:10)
    at AESGCMDecipherBinding.decrypt (####\node_modules\ssh2\lib\protocol\crypto.js:1086:26)
    at Protocol.parsePacket [as _parse] (####\node_modules\ssh2\lib\protocol\Protocol.js:1994:25)
    at Protocol.parse (####\node_modules\ssh2\lib\protocol\Protocol.js:293:16)
    at Socket.<anonymous> (####\node_modules\ssh2\lib\client.js:713:21)
    at Socket.emit (node:events:520:28) {
  code: 2
}
```

ssh2 sftp example, calling .end(), which does not print this error.

```
Outbound: Sending DISCONNECT (11)
Socket ended
Socket closed
```

**Comment by m0rph84** [comment]
I have the same issue. Could it be that the connection is closed too soon?

**Comment by m0rph84** [comment]
This is my code below, I'm using NodeJs+Express, serving scp file copy via REST API. I'm connecting to a Linux server:

const { Client } = require('node-scp')

```
async function transferTest() {
 try {
  let remotePath = '/somepath/test.txt';
  let localPath = './test.txt'
   const client = await Client({
     host: 'myhost',
     port: 22,
     username: 'user',
     password: '1234',
   })
   await client.uploadFile(
     localPath,
     remotePath,
     console.log("File transfered")
   )
   client.close()
 } catch (e) {
   console.log(e)
 }
}

module.exports.upFiles = async function () {
 const transf = await transferTest();
}
```

The copy is working perfectly but when is time to close the connection I get the error:

```
Error during closing sftpWrapper Error: No such file
    ....
  code: 2
```

**Comment by hanzhangyu** [comment]
same to me

**Comment by Jmunb** [comment]
same to me

**Comment by maitrungduc1410** [comment]
Hi all, thanks for your feedback, I'll look into this issue

**Comment by Ithuangzhihang** [comment]
![image](https://user-images.githubusercontent.com/96850465/202845696-1249e72d-0110-4f78-a197-e7fcc23fa7ad.png)
提交成功以后，显示这样的问题

**Comment by maitrungduc1410** [comment]
hi all, please upgrade to `v0.0.22`, I fixed this issue. Thanks for your feedback

**Comment by aldhi88** [comment]
![image](https://user-images.githubusercontent.com/16351933/203875028-dcd0c1ea-b41a-4940-a8e8-859479eed98d.png)

**Comment by aldhi88** [comment]
> hi all, please upgrade to `v0.0.22`, I fixed this issue. Thanks for your feedback

not working
